"use client";

type Props = {
  params: { slug: string };
};

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yl0DkQhnbr8
 */

import { getData } from "@/helpers/getData";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { useEffect } from "react";
import Loading from "@/app/loading";
import { Post } from "@/index";
import DOMPurify from "dompurify";

export default function Page({ params: { slug } }: Props) {
  const { data, isLoading } = useQuery({
    queryKey: ["getPostById"],
    queryFn: async () => await getData(`/api/posts/${slug}`),
    // select: (data) => data.post,
  });

  const post: Post = data?.post;

  const htmlSanitizer = (content: string) => ({
    __html: DOMPurify.sanitize(content),
  });

  // useEffect(() => {
  //   console.log(post);
  // }, [post]);

  return (
    // <div className="grid md:grid-cols-[minmax(200px_1fr)] gap-6 max-w-5xl mx-auto items-start px-4 py-6 md:px-6 md:py-12">
    <div className="grid md:grid-cols-[minmax(200px_1fr)] gap-6 mx-auto items-start w-full">
      {isLoading && <Loading />}
      {post && (
        <div className="space-y-4">
          <div className="space-y-2 not-prose">
            <h2 className="text-3xl font-extrabold tracking-tight lg:text-4xl">
              {post.title}
            </h2>
            <p className="text-gray-500 dark:text-gray-400">
              {post.date?.toString()}
            </p>
          </div>
          <article className="prose prose-gray max-w-none not-italic space-y-8">
            <div dangerouslySetInnerHTML={htmlSanitizer(post?.content)} />
          </article>
        </div>
      )}

      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold tracking-tight">
            You Might Not Like...
          </h2>
          <p className="text-gray-500 dark:text-gray-400">
            Because they&#39;re just randomly picked.
          </p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Art of the Dad Joke
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on June 12, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Science of Silliness
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on April 30, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Joy of Jokes
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on February 14, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Laughter Library
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on December 25, 2022
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
