import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>
          <div className="bg-gray-100 dark:bg-gray-900 min-h-screen">
            <div className="py-6 md:py-12 lg:py-16 xl:py-20">
              <div className="container px-4 md:px-6">
                <div className="grid gap-6 md:gap-8">
                  <Header />
                  {children}
                </div>
              </div>
            </div>
          </div>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
