"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yl0DkQhnbr8
 */

import { getData } from "@/helpers/getData";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Fragment, Suspense, useEffect } from "react";
import { ArticleAttributes, Paragragh } from "..";
import { v4 } from "uuid";
import Loading from "@/app/loading";

const fontFormat = ({ bold, italic, strikethrough, underline }: Paragragh) => {
  let fontArray: string[] = [];

  if (bold) fontArray = [...fontArray, "font-bold"];
  if (italic) fontArray = [...fontArray, "italic"];
  if (strikethrough) fontArray = [...fontArray, "line-through"];
  if (underline) fontArray = [...fontArray, "underline"];

  return fontArray.join(" ");
};

export function Article({ articleId }: { articleId: string }) {
  const { data, isLoading } = useQuery({
    queryKey: ["getOneArticle"],
    queryFn: async () => await getData(`/api/articles/${articleId}`),
  });

  const articleAttributes: ArticleAttributes = data?.data.attributes;

  // useEffect(() => {
  //   console.log(articleId);
  // }, [articleId]);

  return (
    // <div className="grid md:grid-cols-[minmax(200px_1fr)] gap-6 max-w-5xl mx-auto items-start px-4 py-6 md:px-6 md:py-12">
    <div className="grid md:grid-cols-[minmax(200px_1fr)] gap-6 mx-auto items-start">
      <div className="space-y-4">
        <div className="space-y-2 not-prose">
          {isLoading && <Loading />}
          {data && (
            <>
              <h1 className="text-3xl font-extrabold tracking-tight lg:text-4xl">
                {articleAttributes.Title}
              </h1>
              <p className="text-gray-500 dark:text-gray-400">
                {articleAttributes.Date}
              </p>
            </>
          )}
        </div>
        <article className="prose prose-gray max-w-none not-italic space-y-8">
          {data && (
            <>
              {articleAttributes.Content.map((paragraph) => (
                <Fragment key={v4()}>
                  {paragraph && (
                    <p
                      className={
                        // `${paragraph.children[0].italic ? "italic" : ""}
                        // ${paragraph.children[0].bold ? "font-bold" : ""}`
                        fontFormat(paragraph.children[0])
                      }
                      key={v4()}
                    >
                      {paragraph.children[0].text}
                    </p>
                  )}
                </Fragment>
              ))}
            </>
          )}
        </article>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold tracking-tight">
            You Might Not Like...
          </h2>
          <p className="text-gray-500 dark:text-gray-400">
            Because they&#39;re just randomly picked. 0% Algorithm.
          </p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Art of the Dad Joke
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on June 12, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Science of Silliness
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on April 30, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Joy of Jokes
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on February 14, 2023
            </p>
          </div>
          <div className="flex flex-col gap-1.5">
            <Link className="font-medium" href="#">
              The Laughter Library
            </Link>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Posted on December 25, 2022
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
