"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/20tJpmmWf5L
 */

import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Fragment, Key, useEffect } from "react";
import Loading from "@/app/loading";
import { ChevronRightIcon } from "lucide-react";
import { getData } from "@/helpers/getData";
import { HomePost, Post } from "..";
import DOMPurify from "dompurify";

export function BlogHome() {
  const { data: posts, isLoading } = useQuery({
    queryKey: ["fetchAllPosts"],
    queryFn: async () => await getData("/api/posts/blog-home"),
    select: (data) => data.posts.edges,
  });

  // useEffect(() => {
  //   console.log(posts);
  // }, [posts]);

  isLoading && <Loading />;

  const htmlSanitizer = (content: string) => ({
    __html: DOMPurify.sanitize(content),
  });

  return (
    <div className="grid gap-6 md:gap-8">
      {posts &&
        posts.map((post: HomePost) => {
          return (
            <Fragment key={post.node.id}>
              <div className="space-y-2">
                <Link className="inline-flex" href={`/posts/${post.node.id}`}>
                  <h2 className="text-3xl font-bold tracking-tight">
                    {post.node.title}
                  </h2>
                </Link>
                <p className="text-gray-500 dark:text-gray-400">
                  {new Date(post.node.date).toLocaleDateString()}
                </p>
              </div>
              <div className="space-y-4">
                <div className=" line-clamp-2">
                  <div
                    dangerouslySetInnerHTML={htmlSanitizer(post.node.content)}
                  />
                </div>
                <div className="mt-4">
                  <Link
                    className="font-semibold underline hover:underline inline-flex items-center"
                    href={`/posts/${post.node.id}`}
                  >
                    Read more
                    <span>
                      <ChevronRightIcon className="w-4 h-4" />
                    </span>
                  </Link>
                </div>
              </div>
            </Fragment>
          );
        })}
    </div>
  );
}
